---
- name: demo of webserver
  hosts: all
  #gather_facts: false
   
  tasks:
   - name: task1
     ansible.builtin.yum:
      name: "{{mypkg1}}"
      state: present
     tags:
       justinstall
   - name: task2
     ansible.builtin.service:
      name: "{{mysvc1}}"
      state: started
      enabled: yes
   - name: task3
     ansible.builtin.copy:
      src: index.html
      dest: /var/www/html
   - name: task4
     ansible.posix.firewalld:
      state: enabled
      service: http
      immediate: true
      permanent: true

...
